### ISSUE TITLE
方便给个联系方式吗

### ISSUE THREAD

**Issue by GitNealian** [fuyuntt/chess-gui#4]
[https://github.com/pengjiu/ChineseChess](https://github.com/pengjiu/ChineseChess)
这个项目的棋力不错，出于学习目的，想翻译一下，由于您有写cchess的经验，若遇到问题希望可以向您请教

**Comment by fuyuntt** [comment]
给你个我写的文档：[中国象棋对弈程序](https://bytedance.feishu.cn/docs/doccn1fXsPHHjcQh9VUtPHD9KGd)，很多内容是参考的网站[象棋百科全书](https://www.xqbase.com/)
我qq号：983174596
